#!/usr/bin/env bash
set -euo pipefail
set -x

linux_pkg=$1

kernel_release=$(cat $linux_pkg/kernel.release)

. ./env.sh

./scripts/target-scpsh "echo '

Please do not use this system!

As of $(date), it is used as System-under-Test for evaluation by $USER running
control scripts on $(hostname). If possible, migrate all your /srv/scratch data
to another machine to ensure it is not lost in a clean-install. If you believe
this is outdated, or you can not switch to another machine, contact $NAME
<$EMAIL>.

' | sudo tee /etc/motd"

./scripts/target-linux-deb-install $linux_pkg
./scripts/target-grub-boot -r $kernel_release
