#!/usr/bin/env bash
set -euo pipefail
set -x

linux_pkg=$1

kernel_release=$(cat $linux_pkg/kernel.release)

. ./env.sh

./scripts/target-linux-deb-install $linux_pkg
./scripts/target-grub-boot -r $kernel_release
