#!/bin/env bash
set -euo pipefail
bash -n "$(command -v "$0")"

VM_OLD="$1"
VM_NEW="$2"
RECEIPT="${@:2}"

. ./env.sh
. ./target.sh
ssh="ssh -o BatchMode=true -o NoHostAuthenticationForLocalhost=true"

cp -f $VM_OLD.qcow2 $VM_NEW.qcow2
./scripts/qemu-debian-boot $VM_NEW $BZIMAGE &

# Await boot
while ! ${ssh} -p ${SSH_PORT} ${SSH_DEST} true
do
    sleep 1
    export SSH_PORT=$(cat $VM_NEW.ssh_port)
done

./scripts/target-scpsh $RECEIPT

./scripts/target-scpsh 'systemctl poweroff'
rm -f $SSH_PORT
wait
