#!/bin/env bash
set -eu
set -x

# Brings the VM online such that it is reachable using SSH.

vm_ssh_port=$1
vm_hda=$2
kernel=$3

random_port() {
    # https://unix.stackexchange.com/questions/55913/whats-the-easiest-way-to-find-an-unused-local-port
    comm -23 <(seq 49152 65535 | sort) <(ss -Htan | awk '{print $4}' | cut -d':' -f2 | sort -u) \
        | shuf \
        | head -n 1
}

if [ -e ${vm_ssh_port} ]
then
    echo "Warning: ${vm_ssh_port} already exists, checking if vm is reachable" > /dev/stderr

    ssh_dst=root@localhost
    ssh_port=$(cat ${vm_ssh_port})
    ssh="ssh ${ssh_dst} -p ${ssh_port} -o BatchMode=true -o NoHostAuthenticationForLocalhost=true"

    if ${ssh} "true"
    then
        exit 1
    fi
    rm -f ${vm_ssh_port}
fi

kernel_flag=''
append=''
if [ ${kernel} != "/dev/null" ]
then
    # Beware that the kernel might not find the appropriate modules on it's root
    # filesystem.
    kernel_flag="-kernel ${kernel}"
    append='console=ttyS0 root=/dev/sda1 nokaslr loglevel=15'
fi

ssh_port=$(random_port)
hostname=$(basename ${vm_hda} .qcow2)
echo -n ${ssh_port} > ${vm_ssh_port}

qemu-system-x86_64 \
    -hda ${vm_hda} ${kernel_flag} -append "${append}" \
    -smp cpus=2 \
	-m 2048 \
    -nographic \
    -enable-kvm \
    -netdev user,id=net0,net=10.0.2.0/24,hostname=$hostname,domainname=local,hostfwd=tcp::${ssh_port}-:22 \
	-device e1000,netdev=net0,mac=52:54:98:76:54:32
