#!/bin/bash
{
    set -euo pipefail
    bash -n "$(command -v "$0")"
    set -x

    LINUX=$1
    TARGET=$2
    DST=$3

    if [[ "${TARGET}" != *deb-pkg ]]
    then
       exit 1
    fi

    KERNEL_RELEASE=$(./scripts/linux-release.sh $LINUX)

    mkdir -p .build/$(basename $0)-cache/
    cached=.build/$(basename $0)-cache/$KERNEL_RELEASE
    if [ -d $cached ]
    then
       rm -rfd "${DST}"
       cp -rfd $cached $DST
       exit 0
    fi

    RM="rm -rfd"
    if which trash
    then
       RM=trash
    fi

    set +e
    $RM linux-*_amd64.buildinfo
    $RM linux-*_amd64.changes
    $RM linux-headers-*_amd64.deb
    $RM linux-image-*_amd64.deb
    $RM linux-image-*_amd64.deb
    $RM linux-libc-dev_*_amd64.deb
    set -e

    LOCALVERSION=$(./scripts/linux-localversion.sh $LINUX)
    MAKE=${MAKE:-make -j `getconf _NPROCESSORS_ONLN`}
    MAKE="$MAKE LOCALVERSION=$LOCALVERSION"

    # Compress with xz even on Ubuntu to avoid
    # https://github.com/yktoo/indicator-sound-switcher/issues/113
    env - PATH=${PATH} KDEB_COMPRESS=xz \
        ${MAKE} -C ${LINUX} ${TARGET}
    ccache -s

    TMP=$(mktemp -d --suffix -$USER-$(basename $0))/

    ls -al > "${TMP}kernel.filenames"
    mv linux-*_amd64.buildinfo "${TMP}linux_amd64.buildinfo"
    mv linux-*_amd64.changes "${TMP}linux_amd64.changes"
    mv linux-headers-${KERNEL_RELEASE}_*-*_amd64.deb "${TMP}linux-headers_amd64.deb"
    mv linux-image-${KERNEL_RELEASE}_*-*_amd64.deb "${TMP}linux-image_amd64.deb"
    set +e
    mv linux-image-${KERNEL_RELEASE}-dbg_*-*_amd64.deb "${TMP}linux-image-dbg_amd64.deb"
    set -e
    mv linux-libc-dev_*_amd64.deb "${TMP}linux-libc-dev_amd64.deb"
    echo ${KERNEL_RELEASE} > "${TMP}kernel.release"

    rm -rfd "${DST}"
    cp -rfd $TMP $cached
    mv -f $TMP "$DST"

    exit
}
