#!/usr/bin/env bash
#
# https://stackoverflow.com/questions/2336977/can-a-shell-script-indicate-that-its-lines-be-loaded-into-memory-initially
{
    set -euo pipefail
    bash -n "$(command -v "$0")"

    # Avoid concurrent apt install commands on target.
    flock --nonblock .build/$(basename $0).flock $0.sh "$@" \
        || echo "You may have to run the following: rm $(pwd)/.build/$(basename $0).flock" 1>&2

    exit
}
