#!/usr/bin/env bash
set -euo pipefail
set -x

linux_pkg=$1

. ./env.sh

kernel_release=$(cat $linux_pkg/kernel.release)
cmdline=${GRUB_CMDLINE_LINUX:-}

booted_cmdline=$(./scripts/target-scpsh 'cat /proc/cmdline')
booted_release=$(./scripts/target-scpsh 'uname -r')
if [ "${booted_release}" = "${kernel_release}" ] && [[ "${booted_cmdline}" = *${cmdline}* ]]
then
    exit 0
fi
echo "Booting ${kernel_release} from ${booted_release}" >&2

./scripts/target-scpsh "echo '
Please do not use this system!

As of $(date), it is used as System-under-Test for evaluation by $USER running
control scripts on $(hostname). If possible, migrate all your /srv/scratch data
to another machine to ensure it is not lost in a clean-install. If you believe
this is outdated, or you can not switch to another machine, contact $NAME
<$EMAIL>.
' | sudo tee /etc/motd"

./scripts/target-linux-deb-install $linux_pkg
./scripts/target-grub-boot -r $kernel_release
