#!/usr/bin/env bash
#
# https://stackoverflow.com/questions/2336977/can-a-shell-script-indicate-that-its-lines-be-loaded-into-memory-initially
{
    set -euo pipefail
    bash -n "$(command -v "$0")"

    "$0.sh" "$@"

    exit
}
