#!/bin/bash
set -euo pipefail
bash -n "$(command -v "$0")"
set -x

LINUX_DEB_DIR=$1

kernel_release=$(cat $LINUX_DEB_DIR/kernel.release)

if ./scripts/target-scpsh "dpkg -l | grep '$kernel_release'" && ./scripts/target-scpsh "grep '$kernel_release' /boot/grub/grub.cfg"
then
   exit 0
fi

./scripts/target-scpsh -C target-scripts './linux-deb-cleanup.sh'

./scripts/target-scpsh -C $LINUX_DEB_DIR '
set -x
sudo --non-interactive apt-get -y --allow-downgrades install ./*.deb
'
