#!/usr/bin/env bash
set -euo pipefail
bash -n "$(command -v "$0")"

set -x

# Arguments from suite runner:
dst=$(realpath $1)
burst_len=$2

export BPF_OBJ=${BPF_PROG}.bpf.o

# TODO: Maybe it's not a good idea to send the whole env to the target. Use
# make-style var=value args instead.
env_exports="$(export -p)"

pushd ../system

# Also sets default SuT ($T) and related variables.
. ./env.sh

# Boots target with linux-build ready for target-scpsh.
make all

make -C bpf-samples .build/$BPF_OBJ

wd=$(mktemp -d)
cp bpf-samples/.build/$BPF_OBJ $wd/$BPF_OBJ
./scripts/target-scpsh -o ${dst}/.tmp-$(basename $0) -C $wd -f ./target-scripts/bench-bpftool.sh "
${env_exports}
chmod +x ../file
../file ../result_dir ${burst_len}
"
rm -rfd $wd

mv --no-clobber --target-directory=${dst} ${dst}/.tmp-$(basename $0)/*
rm -d ${dst}/.tmp-$(basename $0)
