#!/usr/bin/env bash
set -euo pipefail
bash -n "$(command -v "$0")"

set -x

# Arguments from suite runner:
output_abs=$1
burst_len=$2

# Environment from suite definition:
CPUFREQ=${CPUFREQ:-max}
PERF_EVENTS=${PERF_EVENTS:-"-e instructions -e iTLB-load-misses -e dTLB-load-misses -e branch-misses"}

pushd ../system

# Also sets default SuT ($T) and related variables.
. ./env.sh

# https://gitlab.cs.fau.de/i4/infra/wake-on-lan
if [[ $T = faui49* ]]
then
	ssh i4lab1 wake $T
fi

# Boots target with linux-build ready for target-scpsh.
make all

# https://www4.cs.fau.de/dokuwiki/labor:systeme?s[]=system&s[]=mode#tips_und_tricks_zur_exklusiven_nutzung_der_fai_laborinstallation
#
# Mabe move this into lib for use in other bench scripts.
if ./scripts/target-scpsh "which set-system-mode"
then
	./scripts/target-scpsh "set-system-mode evaluation"
	export SSH_PORT=23
fi

if ./scripts/target-scpsh 'cat /var/run/fai/fai*_is_running'
then
   exit 1
fi

./scripts/target-scpsh 'uname -a' > ${output_abs}/uname-a
./scripts/target-scpsh 'lscpu'    > ${output_abs}/lscpu

./scripts/target-scpsh "echo 0 > sudo tee /proc/sys/kernel/nmi_watchdog"

if ./scripts/target-scpsh 'ls /sys/devices/system/cpu/cpu0/cpufreq/ > /dev/null'
then
	old_governor=$(./scripts/target-scpsh 'cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor')

	if [[ "${CPUFREQ}" == "max" ]]
	then
		cpufreq_khz=$(./scripts/target-scpsh 'cat /sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_max_freq')
	else
		if ./scripts/target-scpsh "cat /sys/devices/system/cpu/cpu0/cpufreq/base_frequency > /dev/null"
		then
			cpufreq_khz=$(./scripts/target-scpsh "cat /sys/devices/system/cpu/cpu0/cpufreq/base_frequency")
		elif [ $T = faui49easy7 ]
		then
			cpufreq_khz=2800000 # highest available non-boost freq
		else
			set +e
			./scripts/target-scpsh "set-system-mode normal"
			set -e
			exit 1
		fi
	fi
	./scripts/target-scpsh "sudo cpupower frequency-set --min ${cpufreq_khz}kHz --max ${cpufreq_khz}kHz --governor performance"
	./scripts/target-scpsh 'sudo cpupower frequency-info' > ${output_abs}/cpupower-frequency-info
fi

./scripts/target-scpsh 'grep . /sys/devices/system/cpu/vulnerabilities/*' > ${output_abs}/cpu-vulnerabilities

set +e
./scripts/target-scpsh -o "${output_abs}/workload" "
sync
echo 3 | sudo tee /proc/sys/vm/drop_caches > /dev/null
sleep 1
for burst_pos in \$(seq 0 \$(expr ${burst_len} - 1))
do
env -i sudo --preserve-env \$(which perf_\$(uname -r)) stat --output ../result_dir/\${burst_pos}.perf -x , \
-e duration_time \
-e task-clock \
-e raw_syscalls:sys_enter \
${PERF_EVENTS} \
${WORKLOAD} \
> ../result_dir/\${burst_pos}.stdout 2> ../result_dir/\${burst_pos}.stderr
done
"
exitcode=$?
set -e

td=$(mktemp -d)
./scripts/target-scpsh -o ${td}/result_dir 'sudo cat /sys/kernel/debug/tracing/trace > ../result_dir/trace || true'
mv ${td}/result_dir/trace ${output_abs}/trace
rm -rfd ${td}

./scripts/target-scpsh "sudo dmesg" > ${output_abs}/dmesg

# TODO: Always do the following reset commands, even if something else failed.

./scripts/target-scpsh "echo 1 > sudo tee /proc/sys/kernel/nmi_watchdog"

if ./scripts/target-scpsh 'ls /sys/devices/system/cpu/cpu0/cpufreq/ > /dev/null'
then
	min_freq_khz=$(./scripts/target-scpsh "cat /sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_min_freq")
	max_freq_khz=$(./scripts/target-scpsh "cat /sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_max_freq")
	./scripts/target-scpsh "sudo cpupower frequency-set --min ${min_freq_khz}kHz --max ${max_freq_khz}kHz --governor ${old_governor}"
fi

if ./scripts/target-scpsh "which set-system-mode"
then
	./scripts/target-scpsh "set-system-mode normal"
	export SSH_PORT=22
fi

echo -n $exitcode > ${output_abs}/workload-exitcode
