#!/usr/bin/env bash
set -euo pipefail
bash -n "$(command -v "$0")"

set -x

# Arguments from suite runner:
dst=$(realpath $1)
burst_len=$2

pushd ../system

# Also sets default SuT ($T) and related variables.
. ./env.sh

# Boots target with linux-build ready for target-scpsh.
make all

# TODO: Maybe it's not a good idea to send the whole env to the target.
exports="$(export -p)"

./scripts/target-scpsh -o ${dst}/result_dir -f ./target-scripts/bench-workload-perf.sh "
${exports}
chmod +x ../file
../file ../result_dir ${burst_len}
"

mv --no-clobber --target-directory=${dst} ${dst}/result_dir/*
rm -rfd ${dst}/result_dir
