#!/usr/bin/Rscript

source("plotly-preamble.R")

DATA <- DATA %>%
  filter(!str_detect(BPF_OBJ, ".*custom_.*"))

## summary(DATA)
## print(DATA)

cns <- colnames(DATA)
metrics <- cns[cns == "bpftool_loadall_exitcode"]

for (m in metrics) {
 p <- ggplot(DATA, aes(x=paste(BPF_OBJ, " ", bpftool_prog, "()", sep=""), y=get(m), colour=paste(CAPSH_ARGS, SYSCTL))) +
    geom_boxplot() +
    theme(axis.text.x = element_text(angle = 45, hjust=1)) +
    facet_grid(rows=vars(T), labeller=label_both, scales="free")
  eval_save(p, paste0(m, "-point"))
}

## DATA <- DATA %>%
##   filter(bpftool_loadall_exitcode == 0)
## cns <- colnames(DATA)
## metrics <- cns[startsWith(cns, "bpftool_jited_insncnt_") |
##                cns == "bpftool_run_exitcode"]

## for (m in metrics) {
##  p <- ggplot(DATA, aes(x=paste(BPF_OBJ, " ", bpftool_prog, "()", sep=""), y=get(m), colour=paste(CAPSH_ARGS, SYSCTL))) +
##     geom_boxplot() +
##     theme(axis.text.x = element_text(angle = 45, hjust=1)) +
##     facet_grid(rows=vars(T), labeller=label_both, scales="free")
##   eval_save(p, paste0(m))
## }
