#!/usr/bin/Rscript

source("plotlib.R")

cns <- colnames(DATA)
perf_metrics <- cns[startsWith(cns, "perf_") & ! startsWith(cns, "perf_counter_run_time_")]
for (m in perf_metrics) {
  print(m)
  ggplot(DATA, aes(y=paste(WORKLOAD), x=get(m), colour=SYSCTL)) +
    geom_smooth(linetype = "dashed", method = "lm") +
    geom_jitter() +
    scale_y_discrete(labels = function(y) str_wrap(y, width = 40)) +
    facet_grid(rows=vars(hostname_short, workload_exitcode),
               cols=vars(uname_a, CPUFREQ, bench_script),
               labeller=label_both, scales="free")
  eval_save(paste0(m, "-point"))
}
