#!/usr/bin/Rscript

source("plotlib.R")

print(DATA)

ed <- DATA
expr <- ed %>%
  group_by(BPF_OBJ, .drop=F) %>%
  summarize(ble_max = max(bpftool_loadall_exitcode), ble_min = min(bpftool_loadall_exitcode)) %>%
  ungroup()
expr <- ed %>%
  inner_join(expr) %>%
  filter(ble_min == 0) %>%
  distinct(BPF_OBJ, LINUX_GIT_CHECKOUT, SYSCTL, .keep_all=TRUE)

ggplot(expr, aes(paste(LINUX_GIT_CHECKOUT, SYSCTL),
                 ## colour=paste(`BPF Loadable`, bpftool_loadall_error, bpftool_loadall_error_reason),
                 fill=paste(verification_error_speculative, verification_error),
                 )) +
  geom_histogram(stat = "count") +
  theme(axis.text.x = element_text(angle = 45, hjust=1)) +
  scale_fill_viridis_d() +
  facet_grid(cols=vars(Project), rows=vars(`BPF Program Type`), scales="free")
eval_save("verierror")

d <- expr %>%
  filter(!verification_error_speculative)
ggplot(d, aes(paste(verification_error_speculative, verification_error),
              fill=paste(LINUX_GIT_CHECKOUT, SYSCTL))) +
  geom_histogram(stat = "count", position="dodge") +
  theme(axis.text.x = element_text(angle = 45, hjust=1))
eval_save("v1-lfence-nospec-errors")

## d <- d %>%
##   filter(LINUX_GIT_CHECKOUT == "bpf-spectre-v1-lfence")
print(d$BPF_OBJ)
ggplot(d, aes(verification_error, paste(BPF_OBJ), colour=LINUX_GIT_CHECKOUT)) +
  geom_point() +
  theme(axis.text.x = element_text(angle = 45, hjust=1))
eval_save("obj-nospec-errors")
## BUG: libbpf: failed to load object 'linux-selftests_test_stack_var_off.bpf.o'
##
## CAPSH_ARGS: --drop=
## CPUFREQ: base
## LINUX_GIT_CHECKOUT: bpf-spectre-v1-lfence
## MERGE_CONFIGS: ''
## SYSCTL: kernel.bpf_spec_v1=2
##
## 23: (71) r1 = *(u8 *)(r3 +0)
## R3 variable offset stack read prohibited for spec_v1, var_off=(0x0; 0xf)
##
## Remove throw and check that lfence is added.

ggplot(expr, aes(paste(verification_error), colour=paste(LINUX_GIT_CHECKOUT, SYSCTL),
                 fill=verification_error_speculative)) +
  geom_histogram(stat = "count", position="dodge") +
  theme(axis.text.x = element_text(angle = 45, hjust=1))
eval_save("x")

ggplot(expr, aes(paste(LINUX_GIT_CHECKOUT, SYSCTL), fill=paste(bpftool_loadall_exitcode, verification_error_speculative))) +
  geom_histogram(stat = "count", position="stack") +
  theme(axis.text.x = element_text(angle = 45, hjust=1)) +
  facet_grid(cols=vars(Project), rows=vars(`BPF Program Type`), scales="free")
eval_save("vererror")


d <- DATA %>%
  filter(bpftool_loadall_exitcode == 0, net_core_bpf_jit_harden == "0")
s <- d %>%
  group_by(BPF_OBJ, bpftool_prog, .drop=F) %>%
  summarize(
    bjit_max = max(bpftool_jited_insncnt_total),
    bjit_min = min(bpftool_jited_insncnt_total),
    bjil_max = max(bpftool_jited_insncnt_lfence),
    bjil_min = min(bpftool_jited_insncnt_lfence)
  ) %>%
  ungroup()
d <- d %>%
  left_join(s) %>%
  distinct(BPF_OBJ, bpftool_prog, .keep_all=T)
p <- ggplot(d, aes(`lfence / Total Instructions [%]`, colour=paste(LINUX_GIT_CHECKOUT, SYSCTL))) +
  stat_ecdf() +
  scale_colour_viridis_d()
eval_save("fences")


g <- DATA %>%
  filter(bpftool_run_exitcode == 0, bpftool_loadall_exitcode == 0)
