#!/usr/bin/Rscript

source("plotlib.R")

WRK_DATA <- DATA %>%
  filter(OSE_LOXILB_VALIDATION == "wrk",
         burst_pos > 0) %>%
  pivot_longer(c(`wrk_latency_50.000%_ms`,
                 `wrk_latency_75.000%_ms`,
                 `wrk_latency_90.000%_ms`,
                 `wrk_latency_99.000%_ms`,
                 `wrk_latency_99.900%_ms`,
                 `wrk_latency_99.990%_ms`,
                 `wrk_latency_99.999%_ms`,
                 `wrk_latency_100.000%_ms`),
               names_to = "wrk_latency_quantile",
               names_pattern = "wrk_latency_(.+)%_ms",
               values_to = "wrk_latency_ms") %>%
  mutate(wrk_latency_quantile = as.numeric(wrk_latency_quantile) / 100)

DATA <- DATA %>%
  group_by(uname_a, T, OSE_SYSCTL,
           OSE_LOXILB_VALIDATION, OSE_LATENCY_PAYLOAD_SIZE, OSE_LOXILB_CLIENTS, OSE_LOXILB_SERVERS,
           OSE_WRK_CONNECTIONS, OSE_WRK_RATE, OSE_WRK_EXTRA_FLAGS) %>%
  mutate(across(where(is.numeric), ~ .x / min(.x, na.rm = TRUE), .names = "norm_{.col}"),
         across(where(is.numeric), ~ min(.x, na.rm = TRUE), .names = "min_{.col}"),
         across(where(is.numeric), ~ max(.x, na.rm = TRUE), .names = "max_{.col}")) %>%
  ungroup() %>%
  group_by(uname_a, T, OSE_SYSCTL,
           OSE_LOXILB_VALIDATION, OSE_LATENCY_PAYLOAD_SIZE, OSE_LOXILB_CLIENTS, OSE_LOXILB_SERVERS,
           OSE_WRK_CONNECTIONS, OSE_WRK_RATE, OSE_WRK_EXTRA_FLAGS) %>%
  mutate(across(where(is.numeric), ~ mean(.x, na.rm = TRUE), .names = "mean_{.col}")) %>%
  ungroup()

CLEAN_WRK_DATA <- DATA %>%
  filter(wrk_requests_per_sec > 0.99 * mean_wrk_requests_per_sec,
         wrk_requests_per_sec < 1.01 * mean_wrk_requests_per_sec)

cns <- colnames(DATA)
perf_metrics <- cns[
  startsWith(cns, "wrk_latency_")
  | cns == "wrk_rate"
  | startsWith(cns, "wrk_requests_per_sec")
  | startsWith(cns, "bpftool_prog_show_run_time_")
  | startsWith(cns, "perf_cycles")
  | startsWith(cns, "perf_power")
]
for (m in perf_metrics) {
  for (c in unique(DATA$OSE_WRK_CONNECTIONS)) {
    ggplot(CLEAN_WRK_DATA %>% filter(OSE_LOXILB_VALIDATION == "wrk",
                           OSE_WRK_CONNECTIONS == c),
           aes(x=get(m),
               colour=paste0(kernel_bpf_spec_v1),
               linetype=paste0(kernel_bpf_spec_v4))) +
      stat_ecdf() +
      scale_colour_viridis_d(begin = 0.2, end = 0.8) +
      scale_x_continuous(limits=c(quantile(DATA[[m]], probs=c(.0)),quantile(DATA[[m]], probs=c(.95)))) +
      facet_grid(rows=vars(hostname_short, workload_exitcode, OSE_LOXILB_VALIDATION, OSE_WRK_RATE, OSE_LATENCY_PAYLOAD_SIZE, OSE_LOXILB_CLIENTS, OSE_LOXILB_SERVERS, OSE_WRK_CONNECTIONS),
                 cols=vars(uname_a, OSE_CPUFREQ, bench_script, OSE_WRK_EXTRA_FLAGS),
                 labeller=label_both, scales="free")
    eval_save(paste0(m))

    ggplot(CLEAN_WRK_DATA %>% filter(OSE_LOXILB_VALIDATION == "wrk",
                           OSE_WRK_CONNECTIONS == c),
           aes(y=get(m),
               x=wrk_requests_per_sec)) +
      geom_boxplot(aes(group = cut_width(wrk_requests_per_sec, 500))) +
      scale_colour_viridis_d(begin = 0.2, end = 0.8) +
      facet_grid(rows=vars(hostname_short, workload_exitcode, OSE_LOXILB_VALIDATION, OSE_LATENCY_PAYLOAD_SIZE, OSE_LOXILB_CLIENTS, OSE_LOXILB_SERVERS, OSE_WRK_CONNECTIONS),
                 cols=vars(uname_a, OSE_CPUFREQ, bench_script, kernel_bpf_spec_v1, kernel_bpf_spec_v4, OSE_WRK_EXTRA_FLAGS),
                 labeller=label_both, scales="free")
    eval_save(paste0("rate-", m))
  }
}

ggplot(WRK_DATA,
       aes(x=wrk_latency_quantile,
           y=wrk_latency_ms,
           colour=paste0(kernel_bpf_spec_v1),
           shape=paste0(kernel_bpf_spec_v4))) +
  geom_point() +
  scale_y_log10() +
  facet_grid(rows=vars(hostname_short, workload_exitcode, OSE_LOXILB_VALIDATION, OSE_WRK_RATE, OSE_LATENCY_PAYLOAD_SIZE, OSE_LOXILB_CLIENTS, OSE_LOXILB_SERVERS, OSE_WRK_CONNECTIONS),
             cols=vars(uname_a, OSE_CPUFREQ, bench_script),
             labeller=label_both, scales="free")
eval_save("wrk")
