#!/usr/bin/Rscript

source("plotlib.R")

d <- DATA %>%
  filter(Project != "vbi-new-linux", User == "Privileged", !str_detect(BPF_OBJ, "^*custom_*")) %>%
  filter(bpftool_loadall_exitcode == 0, kernel_bpf_spec_v1 == "0", net_core_bpf_jit_harden == "0")
s <- d %>%
  group_by(BPF_OBJ, bpftool_prog, .drop=F) %>%
  summarize(
    bjit_max = max(bpftool_jited_insncnt_total),
    bjit_min = min(bpftool_jited_insncnt_total),
    bjil_max = max(bpftool_jited_insncnt_lfence),
    bjil_min = min(bpftool_jited_insncnt_lfence)
  ) %>%
  ungroup()
d <- d %>%
  left_join(s) %>%
  filter(kernel_bpf_spec_v4 == "2") %>%
  distinct(BPF_OBJ, bpftool_prog, .keep_all=T)
ggplot(d, aes(`lfence / Total Instructions [%]`, linetype=`BPF Program Type`, colour=Project)) +
  stat_ecdf() +
  labs(y = "eCDF") +
  scale_colour_viridis_d()
  ## facet_grid(cols=vars(BPF_OBJ, bpftool_prog), scales="free")
ggsave(eval_path("count", 0, ".png"), plot=last_plot(), width = PRES_W, height = PRES_H, units="cm")
eval_save("d")

ed <- DATA %>%
  filter(Project != "vbi-new-linux", User == "Privileged", !str_detect(BPF_OBJ, "^*custom_*")) %>%
  filter(kernel_bpf_spec_v4 == "0", net_core_bpf_jit_harden == "0")
expr <- ed %>%
  group_by(BPF_OBJ, .drop=F) %>%
  summarize(ble_max = max(bpftool_loadall_exitcode), ble_min = min(bpftool_loadall_exitcode)) %>%
  ungroup()
expr <- ed %>%
  inner_join(expr) %>%
  distinct(BPF_OBJ, SYSCTL, .keep_all=TRUE) %>%
  filter(ble_min == 0)

p <- ggplot(expr, aes(SYSCTL, fill=`BPF Load`)) +
  geom_histogram(stat = "count", position="stack") +
  scale_fill_viridis_d()
  ## facet_grid(cols=vars(`BPF Program Type`), scales="free")
eval_save("load")
ggsave(eval_path("loading", 0, ".png"), plot=p, width = PRES_W, height = PRES_H, units="cm")
