#!/usr/bin/Rscript

source("plotlib.R")

print(DATA)

DATA <- DATA %>%
  group_by(uname_a, OSE_SYSCTL, OSE_WORKLOAD, OSE_TRACER) %>%
  mutate(across(where(is.numeric), ~ .x / min(.x, na.rm = TRUE), .names = "norm_{.col}"),
         across(where(is.numeric), ~ min(.x, na.rm = TRUE), .names = "min_{.col}"),
         across(where(is.numeric), ~ max(.x, na.rm = TRUE), .names = "max_{.col}")) %>%
  ungroup() %>%
  group_by(uname_a, OSE_SYSCTL, OSE_WORKLOAD, OSE_TRACER) %>%
  mutate(across(where(is.numeric), ~ mean(.x, na.rm = TRUE), .names = "mean_{.col}")) %>%
  ungroup()

cns <- colnames(DATA)
perf_metrics <- cns[
  startsWith(cns, "perf_") & !startsWith(cns, "perf_counter_run_time_")
  | startsWith(cns, "bpftool_prog_show_burst_")
]

for (m in perf_metrics) {
  print(m)
  ggplot(DATA, aes(y=paste(OSE_TRACER), x=get(m), colour=paste(OSE_SYSCTL, LINUX_GIT_CHECKOUT))) +
    geom_boxplot() +
    scale_y_discrete(labels = function(y) str_wrap(y, width = 40)) +
    facet_grid(rows=vars(hostname_short, workload_exitcode, OSE_WORKLOAD),
               cols=vars(OSE_CPUFREQ, bench_script),
               labeller=label_both, scales="free")
  eval_save(paste0(m, "-point"))
}
