#!/usr/bin/Rscript

source("plotlib.R")

print(DATA)

DATA <- DATA %>%
  group_by(uname_a, OSE_SYSCTL, OSE_WORKLOAD, OSE_TRACER) %>%
  mutate(across(where(is.numeric), ~ .x / min(.x, na.rm = TRUE), .names = "norm_{.col}"),
         across(where(is.numeric), ~ min(.x, na.rm = TRUE), .names = "min_{.col}"),
         across(where(is.numeric), ~ max(.x, na.rm = TRUE), .names = "max_{.col}")) %>%
  ungroup() %>%
  group_by(uname_a, OSE_SYSCTL, OSE_WORKLOAD, OSE_TRACER) %>%
  mutate(across(where(is.numeric), ~ mean(.x, na.rm = TRUE), .names = "mean_{.col}")) %>%
  ungroup()

## cns <- colnames(DATA)
## perf_metrics <- cns[startsWith(cns, "bpftool_prog_show_bytes_")
##                     | startsWith(cns, "bpftool_jited_insncnt_lfence")
##                     | startsWith(cns, "bpftool_jited_insncnt_total")]
## for (m in perf_metrics) {
##   ggplot(DATA, aes(y=get(m),
##                    colour=paste(OSE_SYSCTL))) +
##     stat_ecdf() +
##     facet_grid(rows=vars(hostname_short, workload_exitcode),
##                cols=vars(uname_a, OSE_CPUFREQ, bench_script),
##                labeller=label_both, scales="free")
##   eval_save(paste0("ecdf-", m))
## }

cns <- colnames(DATA)
perf_metrics <- cns[startsWith(cns, "perf_")
                    | startsWith(cns, "bpftool_prog_show_run_time_")
                    | startsWith(cns, "bpftool_prog_show_bytes_")
                    | startsWith(cns, "bpftool_jited_insncnt_lfence")
                    | startsWith(cns, "bpftool_jited_insncnt_total")]

## for (m in perf_metrics) {
##   ggplot(DATA, aes(y=get(m),
##                    colour=paste(OSE_SYSCTL))) +
##     stat_ecdf() +
##     facet_grid(rows=vars(hostname_short, workload_exitcode),
##                cols=vars(uname_a, OSE_CPUFREQ, bench_script),
##                labeller=label_both, scales="free")
##   eval_save(paste0("ecdf-", m))
## }

for (m in perf_metrics) {
  print(m)
  ggplot(DATA, aes(y=paste(OSE_TRACER), x=get(m), colour=OSE_SYSCTL)) +
    geom_boxplot(outlier.shape = NA) +
    scale_y_discrete(labels = function(y) str_wrap(y, width = 40)) +
    ## coord_cartesian(xlim=c(quantile(DATA[[m]], probs=c(.0)),quantile(DATA[[m]], probs=c(.95)))) +
    facet_grid(rows=vars(hostname_short, workload_exitcode, OSE_WORKLOAD),
               cols=vars(uname_a, OSE_CPUFREQ, bench_script),
               labeller=label_both, scales="free")
  eval_save(paste0(m, "-point"))
}

## for (m in perf_metrics) {
##   for (t in unique(DATA$OSE_TRACER)) {
##     ## x/y lfence/norm runtime
##     d <- DATA %>%
##       filter(OSE_TRACER == t)
##     ggplot(d, aes(y=get(m),
##                   colour=bpftool_jited_insncnt_lfence,
##                   linetype=paste(OSE_SYSCTL))) +
##       stat_ecdf() +
##       ## xlim(0.00, 0.99) +
##       facet_grid(rows=vars(hostname_short, workload_exitcode),
##                  cols=vars(uname_a, OSE_CPUFREQ, bench_script),
##                  labeller=label_both, scales="free")
##     eval_save(paste(t, m, sep="-"))
##   }
## }
