#!/usr/bin/Rscript

source("plotlib.R")


DATA <- DATA %>%
  filter(burst_pos > 0) %>%
  mutate(bpf_bench_impl = sub("^.+/bench ", "", WORKLOAD),
         bpf_bench_app = str_extract(bpf_bench_impl, "^[a-z]+-")) %>%
  group_by(T, workload_exitcode, burst_pos, CPUFREQ, bench_script,
           bpf_bench_app) %>%
  mutate(across(where(is.numeric), ~ .x / mean(.x, na.rm = TRUE), .names = "norm_{.col}")) %>%
  ungroup()

summary(DATA)

cns <- colnames(DATA)
metrics <- cns[startsWith(cns, "norm_bpf_bench_")]

for (m in metrics) {
  print(m)
  ggplot(DATA, aes(y=bpf_bench_impl, x=get(m), fill=bpf_bench_app, colour=MERGE_CONFIGS)) +
    geom_boxplot() +
    scale_x_log10() +
    facet_grid(rows=vars(T, workload_exitcode),
               cols=vars(CPUFREQ, bench_script),
               labeller=label_both, scales="free")
  eval_save(paste0(m, "-point"))
}
