#!/usr/bin/Rscript

source("plotlib.R")

dura <- DATA %>%
  filter(BPF_OBJ == "lbe_sockfilter.bpf.o"
         | str_detect(BPF_OBJ, "^*init_whole_stack*")
         | str_detect(BPF_OBJ, "^*minimal_legacy"))

summary(dura)
print(dura)

dura <- dura %>%
  filter(bpftool_loadall_exitcode == 0)
dura <- dura %>%
  filter(bpftool_run_exitcode == 0)

ggplot(dura, aes(x=User, y=bpftool_run_duration_ns, colour=SYSCTL)) +
  geom_boxplot() +
  labs(y = "Execution Time [ns]") +
  scale_y_continuous(limits = c(0, NA)) +
  theme(axis.text.x = element_text(angle = 45, hjust=1)) +
  scale_colour_viridis_d() +
  facet_grid(cols=vars(BPF_OBJ, bpftool_prog),
             scales="free")
ggsave(eval_path("duration", 0, ".png"), plot=last_plot(), width = PRES_W, height = PRES_H, units="cm")

ed <- DATA %>%
  filter(User == "Privileged", !str_detect(BPF_OBJ, "^*custom_*"))
expr <- ed %>%
  group_by(BPF_OBJ, .drop=F) %>%
  summarize(ble_max = max(bpftool_loadall_exitcode), ble_min = min(bpftool_loadall_exitcode)) %>%
  ungroup() %>%
  filter(ble_min == 0)
expr <- ed %>%
  inner_join(expr)

ggplot(expr, aes(y=BPF_OBJ, x=SYSCTL, fill=`BPF Loadable`)) +
  geom_raster() +
  scale_fill_viridis_d(begin = 0.0, end = 0.7) +
  theme(axis.text.x = element_text(angle = 33, hjust=1))
ggsave(eval_path("loading", 0, ".png"), plot=last_plot(), width = PRES_W, height = PRES_H, units="cm")
