#!/usr/bin/Rscript

source("plotlib.R")

summary(DATA)

cns <- colnames(DATA)
perf_metrics <- cns[startsWith(cns, "perf_") & ! startsWith(cns, "perf_counter_run_time_")
                    | startsWith(cns, "bpftool_prog_show_")
                    | startsWith(cns, "bpftool_jited_insncnt_lfence")]
for (m in perf_metrics) {
  print(m)
  ggplot(DATA, aes(y=paste(TRACER, WORKLOAD), x=get(m), colour=SYSCTL)) +
    geom_smooth(linetype = "dashed", method = "lm") +
    geom_jitter() +
    scale_y_discrete(labels = function(y) str_wrap(y, width = 80)) +
    facet_grid(rows=vars(hostname_short, workload_exitcode),
               cols=vars(uname_a, CPUFREQ, bench_script),
               labeller=label_both, scales="free")
  eval_save(paste0(m, "-point"))
}
